use std::str::FromStr;
use crate::lexer;
use lexer::*;

grammar;

pub Term: i32 = {
    "circuit" => 0,
    "<id>" => 1,
};

//Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();

extern {
    type Location = lexer::Loc;
    type Error = lexer::LexicalError;

    enum lexer::Tok {
        "circuit" => Tok::Circuit,
        "module" => Tok::Module,
        "flip" => Tok::Flip,
        ":" => Tok::Colon,
        "<id>" => Tok::Ident,
    }
}
